openapi: 3.1.0
info:
  title: Prisma API
  description: ""
  version: 1.0.0
paths: {}
components:
  schemas:
    users:
      type: object
      description: >-
        This table contains check constraints and requires additional setup for
        migrations. Visit https://pris.ly/d/check-constraints for more info.

        This model or at least one of its fields has comments in the database,
        and requires an additional setup for migrations: Read more:
        https://pris.ly/d/database-comments

        This model contains row level security and requires additional setup for
        migrations. Visit https://pris.ly/d/row-level-security for more info.

        This model contains an expression index which requires additional setup
        for migrations. Visit https://pris.ly/d/expression-indexes for more
        info.
      properties:
        instance_id:
          type: string
        id:
          type: string
        aud:
          type: string
        role:
          type: string
        email:
          type: string
        encrypted_password:
          type: string
        email_confirmed_at:
          type: string
          format: date-time
        invited_at:
          type: string
          format: date-time
        confirmation_token:
          type: string
        confirmation_sent_at:
          type: string
          format: date-time
        recovery_token:
          type: string
        recovery_sent_at:
          type: string
          format: date-time
        email_change_token_new:
          type: string
        email_change:
          type: string
        email_change_sent_at:
          type: string
          format: date-time
        last_sign_in_at:
          type: string
          format: date-time
        raw_app_meta_data:
          type: object
        raw_user_meta_data:
          type: object
        is_super_admin:
          type: boolean
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        phone:
          type: string
        phone_confirmed_at:
          type: string
          format: date-time
        phone_change:
          type: string
        phone_change_token:
          type: string
        phone_change_sent_at:
          type: string
          format: date-time
        confirmed_at:
          type: string
          format: date-time
        email_change_token_current:
          type: string
        email_change_confirm_status:
          type: integer
          format: int32
        banned_until:
          type: string
          format: date-time
        reauthentication_token:
          type: string
        reauthentication_sent_at:
          type: string
          format: date-time
        is_sso_user:
          type: boolean
        deleted_at:
          type: string
          format: date-time
        is_anonymous:
          type: boolean
        grades:
          type: array
          items:
            $ref: "#/components/schemas/grades"
        project_students:
          type: array
          items:
            $ref: "#/components/schemas/project_students"
        projects_projects_opponent_idTousers:
          type: array
          items:
            $ref: "#/components/schemas/projects"
        projects_projects_supervisor_idTousers:
          type: array
          items:
            $ref: "#/components/schemas/projects"
        reviews:
          type: array
          items:
            $ref: "#/components/schemas/reviews"
      required:
        - id
        - is_sso_user
        - is_anonymous
        - grades
        - project_students
        - projects_projects_opponent_idTousers
        - projects_projects_supervisor_idTousers
        - reviews
    attachments:
      type: object
      description: This model contains row level security and requires additional
        setup for migrations. Visit https://pris.ly/d/row-level-security for
        more info.
      properties:
        id:
          type: integer
          format: int64
        project_id:
          type: integer
          format: int64
        filename:
          type: string
        storage_path:
          type: string
        description:
          type: string
        uploaded_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        projects:
          $ref: "#/components/schemas/projects"
      required:
        - id
        - filename
        - storage_path
        - uploaded_at
        - updated_at
    external_links:
      type: object
      description: This model contains row level security and requires additional
        setup for migrations. Visit https://pris.ly/d/row-level-security for
        more info.
      properties:
        id:
          type: integer
          format: int64
        project_id:
          type: integer
          format: int64
        url:
          type: string
        title:
          type: string
        description:
          type: string
        added_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        projects:
          $ref: "#/components/schemas/projects"
      required:
        - id
        - added_at
        - updated_at
    grades:
      type: object
      description: This model contains row level security and requires additional
        setup for migrations. Visit https://pris.ly/d/row-level-security for
        more info.
      properties:
        id:
          type: integer
          format: int64
        value:
          type: integer
          format: int64
        year_id:
          type: integer
          format: int64
        project_id:
          type: integer
          format: int64
        reviewer_id:
          type: string
        created_at:
          type: string
          format: date-time
        projects:
          $ref: "#/components/schemas/projects"
        years:
          $ref: "#/components/schemas/years"
        users:
          $ref: "#/components/schemas/users"
      required:
        - id
        - value
        - year_id
        - project_id
        - reviewer_id
        - created_at
        - projects
        - years
        - users
    project_students:
      type: object
      description: This model contains row level security and requires additional
        setup for migrations. Visit https://pris.ly/d/row-level-security for
        more info.
      properties:
        id:
          type: integer
          format: int64
        project_id:
          type: integer
          format: int64
        student_id:
          type: string
        created_at:
          type: string
          format: date-time
        projects:
          $ref: "#/components/schemas/projects"
        users:
          $ref: "#/components/schemas/users"
      required:
        - id
        - project_id
        - student_id
        - projects
        - users
    projects:
      type: object
      description: This model contains row level security and requires additional
        setup for migrations. Visit https://pris.ly/d/row-level-security for
        more info.
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        supervisor_id:
          type: string
        opponent_id:
          type: string
        subject:
          type: string
        description:
          type: string
        main_documentation:
          type: string
        updated_at:
          type: string
          format: date-time
        attachments:
          type: array
          items:
            $ref: "#/components/schemas/attachments"
        external_links:
          type: array
          items:
            $ref: "#/components/schemas/external_links"
        grades:
          type: array
          items:
            $ref: "#/components/schemas/grades"
        project_students:
          type: array
          items:
            $ref: "#/components/schemas/project_students"
        users_projects_opponent_idTousers:
          $ref: "#/components/schemas/users"
        users_projects_supervisor_idTousers:
          $ref: "#/components/schemas/users"
        reviews:
          type: array
          items:
            $ref: "#/components/schemas/reviews"
      required:
        - id
        - title
        - supervisor_id
        - opponent_id
        - subject
        - updated_at
        - attachments
        - external_links
        - grades
        - project_students
        - users_projects_opponent_idTousers
        - users_projects_supervisor_idTousers
        - reviews
    reviews:
      type: object
      description: This model contains row level security and requires additional
        setup for migrations. Visit https://pris.ly/d/row-level-security for
        more info.
      properties:
        id:
          type: integer
          format: int64
        project_id:
          type: integer
          format: int64
        reviewer_id:
          type: string
        comments:
          type: string
        submitted_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        projects:
          $ref: "#/components/schemas/projects"
        users:
          $ref: "#/components/schemas/users"
      required:
        - id
        - project_id
        - reviewer_id
        - comments
        - submitted_at
        - updated_at
        - projects
        - users
    roles:
      type: object
      description: This model contains row level security and requires additional
        setup for migrations. Visit https://pris.ly/d/row-level-security for
        more info.
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        created_at:
          type: string
          format: date-time
        description:
          type: string
        updated_at:
          type: string
          format: date-time
        scale_sets:
          type: array
          items:
            $ref: "#/components/schemas/scale_sets"
      required:
        - id
        - name
        - created_at
        - updated_at
        - scale_sets
    scale_set_scales:
      type: object
      description: This model contains row level security and requires additional
        setup for migrations. Visit https://pris.ly/d/row-level-security for
        more info.
      properties:
        id:
          type: integer
          format: int64
        scale_set_id:
          type: integer
          format: int64
        scale_id:
          type: integer
          format: int64
        weight:
          type: integer
          format: int32
        display_order:
          type: integer
          format: int32
        created_at:
          type: string
          format: date-time
        scales:
          $ref: "#/components/schemas/scales"
        scale_sets:
          $ref: "#/components/schemas/scale_sets"
      required:
        - id
        - scale_set_id
        - scale_id
        - weight
        - created_at
        - scales
        - scale_sets
    scale_sets:
      type: object
      description: This model contains row level security and requires additional
        setup for migrations. Visit https://pris.ly/d/row-level-security for
        more info.
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        role_id:
          type: integer
          format: int64
        year_id:
          type: integer
          format: int64
        created_at:
          type: string
          format: date-time
        scale_set_scales:
          type: array
          items:
            $ref: "#/components/schemas/scale_set_scales"
        roles:
          $ref: "#/components/schemas/roles"
        years:
          $ref: "#/components/schemas/years"
      required:
        - id
        - created_at
        - scale_set_scales
    scales:
      type: object
      description: This model contains row level security and requires additional
        setup for migrations. Visit https://pris.ly/d/row-level-security for
        more info.
      properties:
        id:
          type: integer
          format: int64
        maxVal:
          type: integer
          format: int64
        name:
          type: string
        desc:
          type: string
        created_at:
          type: string
          format: date-time
        scale_set_scales:
          type: array
          items:
            $ref: "#/components/schemas/scale_set_scales"
      required:
        - id
        - maxVal
        - name
        - created_at
        - scale_set_scales
    years:
      type: object
      description: This model contains row level security and requires additional
        setup for migrations. Visit https://pris.ly/d/row-level-security for
        more info.
      properties:
        id:
          type: integer
          format: int64
        school_id:
          type: integer
          format: int64
        assignment_date:
          type: string
          format: date-time
        submission_date:
          type: string
          format: date-time
        feedback_date:
          type: string
          format: date-time
        created_at:
          type: string
          format: date-time
        grades:
          type: array
          items:
            $ref: "#/components/schemas/grades"
        scale_sets:
          type: array
          items:
            $ref: "#/components/schemas/scale_sets"
      required:
        - id
        - created_at
        - grades
        - scale_sets
    status:
      type: string
      enum:
        - draft
        - submitted
        - locked
        - public
  responses: {}
  parameters: {}
  examples: {}
  requestBodies: {}
  headers: {}
  securitySchemes: {}
  links: {}
  callbacks: {}
tags: []
servers: []
